SELECT *
FROM( PROMOCION)
WHERE (rownum<= 20 AND FIN IS NOT NULL)
ORDER BY (FIN-INICIO) ASC;


SELECT *
FROM( PROMOCION)
WHERE (rownum<= 20 AND ID_SUCURSAL = 1 AND FIN IS NOT NULL)
ORDER BY (FIN-INICIO) ASC;

