
/*Consultas para gerente de sucursal*/
--Todas las consultas requieren elegir solo las de la sucursal del gerente
--Precio en cierto rango
SELECT CODIGO_BARRAS,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO,PRECIO_VENTA
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO_SUCURSAL.PRECIO_VENTA BETWEEN '5000' AND '30000') AND PRODUCTO_SUCURSAL.ID_SUCURSAL = 3);

--Fecha vencimiento posterior a una fecha
SELECT NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO.FECHA_VENCIMIENTO > to_date('03/11/2022', 'dd/mm/yyyy')) AND PRODUCTO_SUCURSAL.ID_SUCURSAL = 3);

-- Peso mayor a algun valor
SELECT NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
(
SELECT *
FROM PRODUCTO 
WHERE (UNIDAD_MEDIDA = 'gr' AND CANTIDAD_PRESENTACION > '1000')-- Aqui esta la condicion del peso
)productoGramos
ON(productoGramos.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ( PRODUCTO_SUCURSAL.ID_SUCURSAL = 3);

--Volumen mayor a algun valor
SELECT NOMBRE,MARCA,PRECIO_VENTA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
(
SELECT *
FROM PRODUCTO 
WHERE (UNIDAD_MEDIDA = 'ml' AND CANTIDAD_PRESENTACION > '1000')-- Aqui esta la condicion del peso
)productoml
ON(productoml.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE (PRODUCTO_SUCURSAL.ID_SUCURSAL = 3);

--Cierto tipo 
SELECT NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO.TIPO = 'Carnes') AND PRODUCTO_SUCURSAL.ID_SUCURSAL = 3);

--Cierta categoria
SELECT NOMBRE,MARCA,PRECIO_VENTA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO.CATEGORIA = 'Aseo') AND PRODUCTO_SUCURSAL.ID_SUCURSAL = 3);

--Vendido mas de X unidades en un rango de fechas
SELECT NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO, UNIDADES
FROM (
(
SELECT ID_PRODUCTO, COUNT(*) AS UNIDADES
FROM (
VENTA_PRODUCTO
)
WHERE ((FECHA BETWEEN to_date('03/11/2011', 'dd/mm/yyyy') AND  to_date('03/11/2015', 'dd/mm/yyyy')) AND ID_SUCURSAL = 3 )-- Condicion gerente y rango fechas
GROUP BY ID_PRODUCTO
HAVING COUNT(*)>= 5 -- Aqui esta condicion der mas de x (5) unidades
)productosCumplen
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = productosCumplen.ID_PRODUCTO)
);




/*Consultas para gerente de supermercado*/




--Precio en cierto rango
SELECT ID_SUCURSAL,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO,PRECIO_VENTA
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO_SUCURSAL.PRECIO_VENTA BETWEEN '5000' AND '30000'));

--Fecha vencimiento posterior a una fecha
SELECT ID_SUCURSAL,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO.FECHA_VENCIMIENTO > to_date('03/11/2022', 'dd/mm/yyyy')));

-- Peso mayor a algun valor
SELECT ID_SUCURSAL,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
(
SELECT *
FROM PRODUCTO 
WHERE (UNIDAD_MEDIDA = 'gr' AND CANTIDAD_PRESENTACION > '1000')-- Aqui esta la condicion del peso
)productogr
ON(productogr.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
);

--Volumen mayor a algun valor
SELECT ID_SUCURSAL,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
(
SELECT *
FROM PRODUCTO 
WHERE (UNIDAD_MEDIDA = 'ml' AND CANTIDAD_PRESENTACION > '1000')-- Aqui esta la condicion del peso
)productoml
ON(productoml.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
);

--Cierto tipo 
SELECT ID_SUCURSAL,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO.TIPO = 'Carnes'));

--Cierta categoria
SELECT ID_SUCURSAL,NOMBRE,MARCA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
PRODUCTO_SUCURSAL 
INNER JOIN 
PRODUCTO
ON(PRODUCTO.CODIGO_BARRAS = PRODUCTO_SUCURSAL.ID_PRODUCTO)
)
WHERE ((PRODUCTO.CATEGORIA = 'Aseo'));

--Vendido mas de X unidades en un rango de fechas
SELECT infoCumplen.ID_SUCURSAL,NOMBRE,MARCA,PRECIO_VENTA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO, UNIDADES
FROM (
    (SELECT * 
    FROM(
        (SELECT ID_PRODUCTO, ID_SUCURSAL,COUNT(*) AS UNIDADES
        FROM (VENTA_PRODUCTO)
        WHERE ((FECHA BETWEEN to_date('03/11/2011', 'dd/mm/yyyy') AND  to_date('03/11/2015', 'dd/mm/yyyy')))-- Condicion gerente y rango fechas
        GROUP BY ID_SUCURSAL,ID_PRODUCTO
        HAVING COUNT(*)>= 5 -- Aqui esta condicion der mas de x (5) unidades
        )productosCumplen
        
        INNER JOIN 
        (PRODUCTO)
        ON(PRODUCTO.CODIGO_BARRAS = productosCumplen.ID_PRODUCTO)
    ))infoCumplen
    INNER JOIN 
    (PRODUCTO_SUCURSAL)
    ON (PRODUCTO_SUCURSAL.ID_PRODUCTO = infoCumplen.ID_PRODUCTO AND PRODUCTO_SUCURSAL.ID_SUCURSAL = infoCumplen.ID_SUCURSAL)
);


--Disponibles en ciudad
SELECT ID_SUCURSAL,NOMBRE,MARCA,PRECIO_VENTA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (

    (SELECT productosCiudad.ID_PRODUCTO, PRECIO_VENTA, productosCiudad.ID_SUCURSAL 
    FROM (
        (SELECT ID_PRODUCTO, ID_SUCURSAL
        FROM
        (
            (SELECT ID -- Sucursales que estan en una ciudad
            FROM (SUCURSAL)
            WHERE CIUDAD = 'Bogota')sucursalesCiudad
            INNER JOIN 
            (SELECT ID_PRODUCTO,ALMACEN.ID,ID_SUCURSAL
            FROM(
                PRODUCTO_ALMACEN 
                INNER JOIN 
                ALMACEN 
                ON (PRODUCTO_ALMACEN.ID_ALMACEN = ALMACEN.ID)
                ))almacenSucursal
            ON(sucursalesCiudad.ID = almacenSucursal.ID_SUCURSAL))
        )productosCiudad
        LEFT OUTER JOIN 
        PRODUCTO_SUCURSAL
        ON (PRODUCTO_SUCURSAL.ID_PRODUCTO = productosCiudad.ID_PRODUCTO AND PRODUCTO_SUCURSAL.ID_SUCURSAL = productosCiudad.ID_SUCURSAL)
        )
    )infoCiudad
    INNER JOIN
    PRODUCTO
    
     ON (PRODUCTO.CODIGO_BARRAS = infoCiudad.ID_PRODUCTO)
    
);
--Disponibles en sucursal

SELECT ID_SUCURSAL,NOMBRE,MARCA,PRECIO_VENTA,UNIDAD_MEDIDA,PRESENTACION,CANTIDAD_PRESENTACION,VOLUMEN_EMPAQUE,PESO_EMPAQUE,TIPO,CATEGORIA,FECHA_VENCIMIENTO
FROM (
    (
    SELECT ID_SUCURSAL, ID_PRODUCTO, PRECIO_VENTA
    FROM (PRODUCTO_SUCURSAL)
    WHERE (ID_SUCURSAL = 3))productosDisponibles
    INNER JOIN 
    (PRODUCTO)
    ON(productosDisponibles.ID_PRODUCTO=PRODUCTO.CODIGO_BARRAS)
); 






