DROP SEQUENCE sucuSeq; 
CREATE SEQUENCE sucuSeq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1; 
  
INSERT INTO SUCURSAL(ID, NOMBRE, TELEFONO,DIRECCION,CIUDAD )
VALUES (sucuSeq.nextval,'SuperAndes Central', '3465268','Calle 26 N 15 24', 'Bogota' ); 

INSERT INTO SUCURSAL(ID, NOMBRE, TELEFONO,DIRECCION,CIUDAD )
VALUES (sucuSeq.nextval,'SuperAndes Oriental', NULL,'Calle 45 N 87 12', 'Cali' ); 

INSERT INTO SUCURSAL(ID, NOMBRE, TELEFONO,DIRECCION,CIUDAD )
VALUES (sucuSeq.nextval,'SuperAndes Occidental', '31452676','Calle 89 N 65 13', 'Bogota' ); 

SELECT * 
FROM SUCURSAL;

DELETE FROM SUCURSAL;